### ISSUE TITLE
New error

### ISSUE THREAD

**Issue by miladm12** [cboettig/appl#11]
I tried to run pomdpsol today and I got this error:

Error in exec_program("pomdpsol", args, stdout = f, stderr = stderr) : 
  Call to pomdpsol failed with error: 255

I did re-install appl but still getting this error. 
I'm just running this: appl::pomdpsol("input.pomdpx", "pomdp.policy", precision = 0.1)

**Comment by cboettig** [comment]
Weird. Do the examples / tests in the package still work for you?  What about less precision with example? Can you give me a copy of the input file & I can take a closer look when I get a chance?

**Comment by cboettig** [comment]
Sounds like this is all working now so closing here.
