### ISSUE TITLE
write_pomdp should support XML version, factored MOMDP version

### ISSUE THREAD

**Issue by cboettig** [cboettig/appl#2]

**Comment by miladm12** [comment]
Please check your email! All attached there!

**Comment by cboettig** [comment]
Very nice, thanks!  These look good.  

From a quick look, it appears there's quite a bit of code that is shared between the two writepomdx functions.  Might be better to either combine them into a single function that has an argument determining if it is MOMDP or POMDP forms, or just moving the common code into a separate sub-routine function.  ('do not repeat yourself' is a common coding mantra and makes code maintenance easier down the road).  Possibly the same is true of the readpolicy_MOMDP and the original readpolicy.  Feel free to send these as a pull request to the appl repo too; that's a bit more convenient for review than email.

**Comment by miladm12** [comment]
Great! I wanted to ask you to send me a guide on parallel runs in R. I saw the how you parallelized POMDP runs and it seems fairly simple. Where can I learn more about it?

**Comment by cboettig** [comment]
Parallelization is a bit all over the place (e.g. see https://cran.r-project.org/web/views/HighPerformanceComputing.html), partly because there are many ways to go about it.  But the basics are simple.  R programming (and many other high-level languages) emphasize using 'apply' functions like `lapply` instead of `for` loops for most cases where order is not important.  Such functions are easy to parallelize, usually by just using the parallel equivalents.

The `parallel` package (now part of base R) provides utilities to parallelize common operations, see https://stat.ethz.ch/R-manual/R-devel/library/parallel/doc/parallel.pdf.  The mclapply function we use is just a parallel version of lapply, and in it's default mode just parallelizes over multiple cores of a processor.  the `parallel` package has tools to change the back-end of how parallelization is done, e.g. to use MPI tools for parallelism over processors that don't share access to the same RAM, typical of very large clusters.  (This method requires a bit more care because you have to make sure a copy of the required data, functions etc gets loaded on each node in the cluster).  

Having good function abstractions usually makes it much easier to introduce parallelization.  e.g. the newer approaches from the `dplyr` and `purrr` packages (essentially alternatives to for loops for common tasks) are both faster to begin with and easier to parallelize automatically (see `multidplyr` library).  There's always a bit of an art to figuring out what level to parallelize, which basically means bearing in mind that there's always a computational cost to splitting into threads, so usually starting with the largest independent chunks or outermost loop makes the most sense.

**Comment by cboettig** [comment]
Oh, one more link for a reasonably readable overview: http://michaeljkoontz.weebly.com/uploads/1/9/9/4/19940979/parallel.pdf

**Comment by miladm12** [comment]
Thanks a lot, for the pull request, I don't know how to attach the codes, should I just copy paste the code text there?

**Comment by cboettig** [comment]
Oh right. Just add the functions to the `R/` directory of your fork.  When you push the changes to your fork, GitHub will give you the option to 'create pull request' against cboettig/appl (not `ropensci/appl`, which is jereon's earlier branch).  See https://help.github.com/articles/using-pull-requests/  

It takes a bit of getting used to but makes it easier to compare code and see what changed.

**Comment by miladm12** [comment]
Okay, I think I just pulled the request. Hope did it correctly.
