### ISSUE TITLE
Add example and unit tests for momdp case

### ISSUE THREAD

**Issue by cboettig** [cboettig/appl#4]

**Comment by miladm12** [comment]
I will be working on this full-time from tomorrow, so I can prepare a simple example to demonstrate here. Will keep you posted.

**Comment by miladm12** [comment]
I have updated the writemomdp code and now it can be merged. I will upload the test code for it soon.

**Comment by miladm12** [comment]
I added an example and test of momdp. Let me know if it make sense or it needs any revision. I tried to use the same format that you had for pomdp.

**Comment by miladm12** [comment]
I guess you can close this!
