### ISSUE TITLE
access to edit files

### ISSUE THREAD

**Issue by miladm12** [cboettig/appl#6]
Hi Carl,

I wanted to edit a file (I found a bug) and it did not allow me to push my changes. Do I not have access?

**Comment by cboettig** [comment]
Whoops, should be fixed now

**Comment by cboettig** [comment]
Note that you can also send pull requests, though not always necessary.  It usually a good habit to also add a unit test that would fail before the bug is fixed but pass after.

**Comment by miladm12** [comment]
Just pulled a request for the minor edit I made
